### PR TITLE
Add Tizen renderer

### PR DESCRIPTION
**Pull request by myroot**
To support Tizen platform

image

### CODE REVIEW

**Comment by rotorgames** [comment]
@myroot Thank you it is awesome work. I will review it soon.

**Comment by myroot** [comment]
@rotorgames Hi, Do you have any updates?

**Comment by rotorgames** [comment]
@myroot Hi. I don't have a windows machine and I try to test your PR on mac os right now.

**Comment by EmilAlipiev** [comment]
any news about this? can we get this for tizen please?

**Comment by martijn00** [comment]
@myroot Thanks! I've cherry picked it here https://github.com/rotorgames/Rg.Plugins.Popup/commit/5a459233015dccae8b54670d72b2622d7eebde41

Please do another PR if this needs an update.

**Pull request closed without merging**
