### PR TITLE
Setting UIWindowLevel.Normal during removal

### PR DESCRIPTION
**Pull request by dimonovdd**
### :sparkles: What kind of change does this PR introduce?
This PR fixed issue #658.

I also added [TestCurrentViewController page](https://github.com/dimonovdd/Rg.Plugins.Popup/blob/0d46f10e49378db6dc6835f35f7cc4888b8c3888/Samples/Demo/Pages/TestCurrentViewController.xaml.cs) and the [reference to Xamarin.Essentials](https://github.com/dimonovdd/Rg.Plugins.Popup/blob/0d46f10e49378db6dc6835f35f7cc4888b8c3888/Samples/Demo/Demo.csproj#L19), which we can delete after merging.

### :arrow_heading_down: What is the current behavior?
There was no way to get the current window

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
see related issue

### :memo: Links to relevant issues
#658 

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines 
- [ ] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by LuckyDucko** [comment]
To be clear, the xamarin essentials example is just here for testing reasons? 

Would it be too much to remove this prior to merging?

**Comment by dimonovdd** [comment]
@LuckyDucko Hi
Yes, I didn't delete this so that  maintainers could look and test changes.
If we don't need it anymore, I can delete it.

**Comment by dimonovdd** [comment]
@rotorgames  @LuckyDucko  @martijn00 Hi
These changes are much needed in my current project. 
What should I do to merge this pull request?

**Review by martijn00 — APPROVED** [review]

**Comment by LuckyDucko** [comment]
@martijn00 thanks for taking care of this

@dimonovdd I think the addition of xamarin essentials just for the demo should be fine, I don't know why, but I had it in my head that it would be included in the release nuget aswell as a dependency of a sort. 

Great addition :+1:

**Comment by dimonovdd** [comment]
@LuckyDucko @martijn00 Thanks, I was already going to move the source code Rg.Plugins.Popup with the fixed problem to my project.

**Pull request merged**
