### PR TITLE
Improving iOS PopupPageRenderer to avoid conflicts with external keyboard and inputaccessoryview

### PR DESCRIPTION
**Pull request by chrux**
…oard and inputaccessoryview.

I added a inputaccessoryview to the demo and running to show you how that is shown.

NOW

screen shot 2017-06-09 at 12 14 32 pm

WITH THE FIX

screen shot 2017-06-09 at 12 13 56 pm

### CODE REVIEW

**Comment by rotorgames** [comment]
@chrux Thank you for PR. I will be added in the 1.1.0

**Comment by JKennedy24** [comment]
Be great to get this one merged soon

**Comment by rotorgames** [comment]
@chrux Hi. How did you reproduce it in a simulator?

**Comment by martijn00** [comment]
@chrux Please reopen a new PR on the current code base if this is still an issue

**Pull request closed without merging**
