### PR TITLE
Migrated to AndroidX

### PR DESCRIPTION
**Pull request by KennyDizi**
Migrated to AndroidX

### CODE REVIEW

**Comment by rotorgames** [comment]
Hi. Thank you for your work. Did you test it in projects with AppCompat and AndroidX libraries? I would like to save backward compatibility with old versions of Xamarin.Forms as well.

**Comment by ysmoradi** [comment]
We can use AndroidX in the Android 10 target and legacy approach in Android 9 target using multi-targeting. Many libraries are using this approach these days

**Comment by martijn00** [comment]
Done in https://github.com/rotorgames/Rg.Plugins.Popup/pull/476

**Comment by MitchBomcanhao** [comment]
@martijn00 will there be more detailed release notes about the issues fixed in this version 2.0.0? thanks

**Comment by yasmoradi** [comment]
By multi-targeting I mean android9.0 and android10.0 together!
XF is using legacy for android 9.0 and Android for 10.0
Some other packages such as AcrUserDialogs are doing this too
Thanks for the new changes anyway (-: I appreciate these changes

**Comment by rotorgames** [comment]
@ysmoradi I agree with you. We have to support compat libraries as well. There are many projects which can't be updated to AndroidX.

**Comment by martijn00** [comment]
Many projects should update to AndroidX, just like everyone else. It is a matter of time before this will be enforced by Google or Microsoft, so why burden the maintainers with this?

**Comment by dansiegel** [comment]
@martijn00 I agree that Google will start enforcing the migration to AndroidX but right now it is actually important (and pretty damn easy with multitargeting) to support MonoAndroid9.0 and MonoAndroid10.0 so that people can choose what they want... besides a lot of people haven't actually updated to AndroidX yet... having the ability to update Rg.Plugins.Popup with the legacy Android Support packages is still valuable... for the moment...

**Comment by yasmoradi** [comment]
Best on the following facts, I decided to multi-target both android 9 and 10 sdks together in bit framework.
Note that I applied Obsolete attribute for android 9 build of the nuget package, so people can have a better understanding about the right choice (It's recommended to target android 10/X anyway)

1- I tested vs 16.6 prev2 (the latest available), and I realized the xamarin templates are based on android 9 sdk!
2- Visual studio gets installed with android 9 sdk by default!
3- Daily downloads of android support libraries are 10X times more than androidX nuget packages (3000 vs 300)
4- Not all xamarin developers are aware of AndroidX

There is a code snippet which demonstrates what I did:

```cs
#if Android9
[Obsolete("Bit is going to drop support for Android 9 Sdk. It's recommended to use Android 10 Sdk.")]
public static void Init()
{
     // some codes to initialize bit controls such as bit date time picker.
}
#endif
```

Instead of build error which is not easy to understand, I'm showing them a warning with a custom message which describes the situation (Sorry for my bad English!), so they can handle it on their own.
In upcoming releases of bit framework, I'll drop support for android 9 sdk.

PS
I'd like to help to makes things better as a true fan of Prism/Rg.Plugins.Popup/XF and as a team leader who has several projects based on these awesome libraries.
Thanks

**Pull request closed without merging**
