### PR TITLE
Fix Issue #500. Incorrent offset on Android

### LINKED ISSUE #500: [Android] Popup position incorrect when multitasking due to erroneous keyboardoffset being applied
plugin version: 1.2.0.223

When using more than one app on screen (ie one on top of another), the position of the page content in the popup page will be incorrect, as it will incorrectly apply a keyboard offset to the page content, pushing it to the top of the screen, potentially making it completely inaccessible.

something like this:
image

### PR DESCRIPTION
**Pull request by KirillAshikhmin**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Fix Issue #500 

### :bug: Recommendations for testing
Check app in split screen mode

### :thinking: Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines 
- [X] Relevant documentation was updated
- [X] Rebased onto current develop

### CODE REVIEW

**Comment by LuckyDucko** [comment]
Hey @KirillAshikhmin I'll get about testing this when I can 👍

**Review by LuckyDucko — CHANGES_REQUESTED** [review]
This seems to be working as intended, could you chuck in a `screenRealSize.Dispose();` after if statement and it should be good to go 👍

**Comment by KirillAshikhmin** [comment]
Thx. Fixed. I'm just removed the `screenRealSize `field. It's not necessary.

**Review by LuckyDucko — APPROVED** [review]
All looking good, sorry for the delay :+1:

**Comment by LuckyDucko** [comment]
@martijn00 all good to merge

**Review by martijn00 — APPROVED** [review]

**Pull request merged**
