### PR TITLE
Nullables and C# cleanup

### PR DESCRIPTION
**Pull request by charlesroddie**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Enable nullables and take some of the more straightforward Visual Studio automatic C# suggestions

### :arrow_heading_down: What is the current behavior?

NREs happen because nulls are not handled systematically
There are many warnings from many code issues

### :new: What is the new behavior (if this is a feature change)?

There is less chance of NREs. Not 0 because some Xamarin dependencies haven't been anotated yet.
There are fewer warnings about code issues, but still many (suggesting serious problems around asyncs and IDisposables in the current code).

### :boom: Does this PR introduce a breaking change?

No

### :bug: Recommendations for testing

I don't know how to build this project so can't test. The only error that VS reports is lack of some Android SDK but could that prevent testing on UWP?

### :memo: Links to relevant issues/docs

https://github.com/rotorgames/Rg.Plugins.Popup/issues/582

### :thinking: Checklist before submitting

- [ ] All projects build: unknown
- [x] Follows style guide lines
- [x] Relevant documentation was updated
- [ ] Rebased onto current develop: unknown

### CODE REVIEW

**Comment by LuckyDucko** [comment]
@martijn00 this PR shows errors even in the demo version of the app. It seems some of these changes have caused the plugin to go haywire

**Comment by charlesroddie** [comment]
I should have marked as WIP as I wasn't able to build the main project (either before or after this PR) and so I couldn't test the test projects that depend on it. Can anyone advise on my comment in the description?

> I don't know how to build this project so can't test. The only error that VS reports is lack of some Android SDK but could that prevent testing on UWP?

**Comment by martijn00** [comment]
Sometimes you have to look into the warnings output. Make sure to have the uwp sdk installed and the android as well.

**Comment by charlesroddie** [comment]
I can test when I have a system admin rights then to install an android sdk but I may not have that for a week or two.

**Comment by LuckyDucko** [comment]
@charlesroddie when I said errors, it built fine, but opening the most basic popup showed a runtime bug. 

It seems fine now, as I fixed a misplaced line in your code which was causing the main issue. And @rdeveen fixed uwp issues (cheers mate) so think the obvious bits are sorted

**Pull request merged**
