### PR TITLE
Fixed issue with ScaleX error on Android 9 and 11

### PR DESCRIPTION
**Pull request by zinvob**
https://github.com/rotorgames/Rg.Plugins.Popup/issues/407

- [x] All projects build
- [x] Follows style guide lines 
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by LuckyDucko** [comment]
@zinvob can you show me how you reproduced the code? 

Just curious if instead of the if statement, we could use null-coalesce and null conditional operators to change the code from

```csharp
_defaultOpacity = page.Opacity;
if (double.IsNaN(_defaultOpacity))
    _defaultOpacity = 1;
```

to

```csharp
_defaultOpacity = page?.Opacity ?? 1
```

**Comment by zinvob** [comment]
> _defaultOpacity = page?.Opacity ?? 1
> ```

Page is not null and Opacity is not null (it's NAN). Your sample will just still produce _defaultOpacity = NAN. There must be a NAN check. It seems that this problem is due to the page being partially closed down when checking for Opacity. This seems to give different effects on different versions. On my system I can reproduce it on 9 and 11.

**Review by LuckyDucko — APPROVED** [review]
@zinvob Ah I see, why I wanted some example code so I could verify where you were coming from. 

It's unusual that this affected android only, perhaps there is a deeper issue here concerning timing, if I follow your idea about partially closed pages. I'll keep that in mind. Otherwise, good job 👍

**Review by martijn00 — APPROVED** [review]

**Comment by martijn00** [comment]
@rotorgames My nuget api key has expired. Can you send a new one on Slack or email, or give me direct access to the nuget?

**Comment by nathankim0** [comment]
Wow, I found this pr while having a hard time encountering a ScaleX error in v2.0.0.13. The error was resolved after updating to v2.0.0.14. Thank you very much.

**Pull request merged**
