### PR TITLE
Support of macOS added

### LINKED ISSUE #143: Support macOS with Xamarin.Forms 2.5 on Xamarin.Mac V2.0
Currently support for macOS by Xamarin is in beta with version 2.3.5. Would it be possible to provide a pre-release with macOS support?

### PR DESCRIPTION
**Pull request by YZahringer**
Fix #143

### CODE REVIEW

**Comment by rotorgames** [comment]
@YZahringer Hi. Thank you for your PR. I have reviewed it and I have seen that you duplicated a lot of code, you didn't use the pattern DRY. There are duplicated code in iOS project and Mac project, it is not a good solution but I will read this code and will create mac supporting in the future.

Thanks

**Comment by YZahringer** [comment]
@rotorgames Hi, I fixed by sharing the code that was similar between iOS and Mac. Do you see other fix's?
Thank's for review

**Comment by rotorgames** [comment]
@YZahringer Ok. I will review it soon. But I have a lot of bugs and features which I should implement. Them are priority. But I will not close this PR. 

Thanks again.

**Comment by amirvenus** [comment]
@rotorgames 
Did you have time to review this PR?

**Comment by kpetryla** [comment]
@rotorgames is there any chance to support macos soon?

**Comment by codebeaulieu** [comment]
**+1 on this feature.** I'm working on a mac app right now and would love to use this library in it. I appreciate all of your efforts @rotorgames

**Comment by rotorgames** [comment]
@codebeaulieu I hope @YZahringer will fix the issue which I have found as soon as he can and I will able to review this PR again.

**Comment by rotorgames** [comment]
Any improves for this PR? Would someone like to figure out what is wrong with this PR?

**Comment by MysterDru** [comment]
@rotorgames @YZahringer any updates on this PR? I'd really like to use the popups plugin for the mac app that i'm currently working on.

**Comment by Suplanus** [comment]
Would love to see this in the NuGet release 😘

**Comment by charlesroddie** [comment]
@YZahringer are you able to resolve conflicts?

**Comment by YZahringer** [comment]
Sorry I don't work on the macOS platform anymore. You can create another PR based on this one and fix the different issues.

**Pull request closed without merging**
