### PR TITLE
Xamarin Forms GTK Support

### PR DESCRIPTION
**Pull request by antmurph**
Gtk Demo

Note:
Xamarin Forms GTK still relies upon GTK2 which doesn't support window transparency. Thats why there isnt any obscuring the parent page.

### CODE REVIEW

**Comment by martijn00** [comment]
@antmurph can you update this to be based on the latest develop?

**Comment by RwSgxx** [comment]
Hi @antmurph any updates on this?
Thank you!

**Comment by trungnt2910** [comment]
Why is this closed? I've built the fork locally and it seems to work?

**Comment by LuckyDucko** [comment]
I believe it was because it wasn't rebased onto the develop branch. However @trungnt2910 if you are able to do this and keep it building, that would be great!

**Comment by antmurph** [comment]
I took a look at refactoring this to the new develop branch but it looks like things have changed and MSBuildSdkExtras is now used which doesn't support a TFM for GTK. Ill take another look but it seems the only TFM I can target is net472 which is used for WPF. 

I could always add "Rg.Plugins.Popup.GTK" to the solution as I had it with this PR but that would be defying the projects current convention so I want to shy away from that. @martijn00 Are you familiar with any libraries that handle this problem where both WPF and GTK can be targets?

**Comment by martijn00** [comment]
Yes it is only possible to pick 1 target with 1 .net TFM. So it needs to be a different csproj which will output a seperate nuget. See https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Wpf/MvvmCross.Platforms.Wpf.csproj

**Comment by mhrastegari** [comment]
Any news on this?

**Pull request closed without merging**
