### PR TITLE
Wpf

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**

### CODE REVIEW

**Comment by vividos** [comment]
@rotorgames I'm currently porting an app of mine to WPF and I also use the Rg.Plugins.Popup NuGet package. How can I help to get this PR into the plugin?

**Comment by VladislavAntonyuk** [comment]
> @rotorgames I'm currently porting an app of mine to WPF and I also use the Rg.Plugins.Popup NuGet package. How can I help to get this PR into the plugin?

you have to build your own package based on branch

**Comment by rotorgames** [comment]
@vividos I hope I will have time to have a look at supporting macOS, Tizen, and WPF soon.

**Comment by martijn00** [comment]
It's merged in now.

**Comment by VladislavAntonyuk** [comment]
@martijn00 it is closed by not merged

**Comment by martijn00** [comment]
@VladislavAntonyuk it is manually merged in by me because the branch was outdated

**Pull request closed without merging**
